# Generated by Django 5.2 on 2025-04-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('cantidad_producida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('PAUSADO', 'Pausado'), ('COMPLETADO', 'Completado')], max_length=20)),
                ('motivo_pausa', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apodo', models.CharField(max_length=50, unique=True)),
                ('codigo_empresa', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntervaloMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('MAQUINA', 'Maquina'), ('OPERADOR', 'Operador')], max_length=10)),
                ('motivo', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IntervaloOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('MAQUINA', 'Maquina'), ('OPERADOR', 'Operador')], max_length=10)),
                ('motivo', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField()),
                ('estandar', models.IntegerField(default=0)),
                ('cantidad_pedido', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('cantidad_terminado_proceso', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('cantidad_perdida_proceso', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('terminado_sin_actualizar', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_maquina', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('sigla', models.CharField(default='', max_length=10)),
                ('carga', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('golpes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ot', models.IntegerField(unique=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_proc', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('nro_nota_venta_ot', models.CharField(blank=True, max_length=12, null=True)),
                ('item_nota_venta', models.IntegerField()),
                ('referencia_nota_venta', models.IntegerField(blank=True, null=True)),
                ('codigo_producto_inicial', models.CharField(blank=True, max_length=12, null=True)),
                ('codigo_producto_salida', models.CharField(blank=True, max_length=12, null=True)),
                ('descripcion_producto_ot', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('cantidad_avance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('peso_unitario', models.DecimalField(decimal_places=5, default=0.0, max_digits=19)),
                ('cantidad_mprima', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('observacion_ot', models.CharField(blank=True, max_length=150, null=True)),
                ('multa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proceso', models.CharField(max_length=10)),
                ('sigla', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('carga', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaOrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Programa Producción',
                'verbose_name_plural': 'Programas Producción',
            },
        ),
        migrations.CreateModel(
            name='ReporteDiarioPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('EN_REVISION', 'En Revisión')], default='ABIERTO', max_length=20)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones_cierre', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('PAUSADO', 'Pausado')], default='ACTIVO', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('porcentaje_completado', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bloqueo_hasta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reporte de Supervisor',
                'verbose_name_plural': 'Reportes de Supervisor',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_etapa', models.PositiveIntegerField()),
                ('estandar', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RutaOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RutaPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_etapa', models.PositiveIntegerField()),
                ('estandar', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SituacionOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_situacion_ot', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TareaFragmentada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_planificada_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_planificada_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_real_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_real_fin', models.DateTimeField(blank=True, null=True)),
                ('cantidad_asignada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_pendiente_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_completada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kilos_fabricados', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidades_fabricadas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CONTINUADO', 'Continuado al siguiente día'), ('DETENIDO', 'Detenido')], default='PENDIENTE', max_length=20)),
                ('es_continuacion', models.BooleanField(default=False)),
                ('nivel_fragmentacion', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('motivo_detencion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fecha', 'nivel_fragmentacion'],
            },
        ),
        migrations.CreateModel(
            name='TipoOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tipo_ot', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
