# Generated by Django 5.2 on 2025-04-25 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
        ('JobManagement', '0001_initial'),
        ('Machine', '0001_initial'),
        ('Operator', '0001_initial'),
        ('Product', '0001_initial'),
        ('Utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecuciontarea',
            name='operador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operator.operador'),
        ),
        migrations.AddField(
            model_name='intervalooperador',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operator.operador'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobManagement.empresaot'),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.maquina'),
        ),
        migrations.AddField(
            model_name='intervalomaquina',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.maquina'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Client.cliente'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='JobManagement.empresaot'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='materia_prima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Utils.materiaprima'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Utils.measurementunit'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='unidad_medida_mprima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_of_medida_materia_prima', to='Utils.measurementunit'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JobManagement.empresaot'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='tipos_maquina_compatibles',
            field=models.ManyToManyField(related_name='procesos_compatibles', to='Machine.tipomaquina'),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.proceso'),
        ),
        migrations.AddField(
            model_name='programaordentrabajo',
            name='orden_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.ordentrabajo'),
        ),
        migrations.AddField(
            model_name='programaproduccion',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programaproduccion',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programaordentrabajo',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.programaproduccion'),
        ),
        migrations.AddField(
            model_name='reportediarioprograma',
            name='cerrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_cerrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportediarioprograma',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.programaproduccion'),
        ),
        migrations.AddField(
            model_name='reportesupervisor',
            name='editor_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_editando', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportesupervisor',
            name='programa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporte_supervisor', to='JobManagement.programaproduccion'),
        ),
        migrations.AddField(
            model_name='reportesupervisor',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_supervisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ruta',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.maquina'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.proceso'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='Product.producto'),
        ),
        migrations.AddField(
            model_name='rutaot',
            name='orden_trabajo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruta_ot', to='JobManagement.ordentrabajo'),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='JobManagement.rutaot'),
        ),
        migrations.AddField(
            model_name='rutapieza',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.maquina'),
        ),
        migrations.AddField(
            model_name='rutapieza',
            name='pieza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='Product.pieza'),
        ),
        migrations.AddField(
            model_name='rutapieza',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.proceso'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='situacion_ot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='JobManagement.situacionot'),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operator.operador'),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.programaproduccion'),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='tarea_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragmentos', to='JobManagement.itemruta'),
        ),
        migrations.AddField(
            model_name='tareafragmentada',
            name='tarea_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='continuaciones', to='JobManagement.tareafragmentada'),
        ),
        migrations.AddField(
            model_name='ejecuciontarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='JobManagement.tareafragmentada'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tipo_ot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='JobManagement.tipoot'),
        ),
        migrations.AddConstraint(
            model_name='intervalooperador',
            constraint=models.UniqueConstraint(fields=('operador', 'fecha_inicio'), name='unique_operador_intervalo'),
        ),
        migrations.AlterUniqueTogether(
            name='maquina',
            unique_together={('empresa', 'codigo_maquina')},
        ),
        migrations.AddConstraint(
            model_name='intervalomaquina',
            constraint=models.UniqueConstraint(fields=('maquina', 'fecha_inicio'), name='unique_maquina_intervalo'),
        ),
        migrations.AlterUniqueTogether(
            name='proceso',
            unique_together={('empresa', 'codigo_proceso')},
        ),
        migrations.AlterUniqueTogether(
            name='programaordentrabajo',
            unique_together={('programa', 'orden_trabajo')},
        ),
        migrations.AlterUniqueTogether(
            name='reportediarioprograma',
            unique_together={('programa', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='ruta',
            unique_together={('producto', 'nro_etapa', 'proceso', 'maquina')},
        ),
        migrations.AlterUniqueTogether(
            name='itemruta',
            unique_together={('ruta', 'item', 'maquina', 'proceso')},
        ),
        migrations.AlterUniqueTogether(
            name='rutapieza',
            unique_together={('pieza', 'nro_etapa', 'proceso', 'maquina')},
        ),
        migrations.AlterUniqueTogether(
            name='tareafragmentada',
            unique_together={('tarea_original', 'fecha')},
        ),
    ]
