# Generated by Django 4.1.7 on 2025-03-31 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0003_intervalooperador_intervalomaquina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Terminado', 'Terminado'), ('Detenido', 'Detenido')], max_length=20)),
                ('kilos_fabricados', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidades_fabricadas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.itemruta')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.programaproduccion')),
            ],
            options={
                'unique_together': {('programa', 'item_ruta', 'fecha')},
            },
        ),
    ]
