# Generated by Django 5.2 on 2025-04-21 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0004_reportediario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaFragmentada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('porcentaje_completado', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cantidad_asignada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_completada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('es_continuacion', models.BooleanField(default=False)),
                ('nivel_fragmentacion', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tarea_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragmentos', to='JobManagement.itemruta')),
                ('tarea_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='continuaciones', to='JobManagement.tareafragmentada')),
            ],
            options={
                'ordering': ['fecha', 'nivel_fragmentacion'],
            },
        ),
        migrations.AddField(
            model_name='reportediario',
            name='fragmento_tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='JobManagement.tareafragmentada'),
        ),
    ]
