# Generated by Django 5.2 on 2025-04-30 22:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0002_initial'),
        ('Machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadomaquina',
            options={'verbose_name': 'Estado de Máquina', 'verbose_name_plural': 'Estados de Máquinas'},
        ),
        migrations.RemoveField(
            model_name='estadomaquina',
            name='capacidad_maxima',
        ),
        migrations.RemoveField(
            model_name='estadomaquina',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='estadomaquina',
            name='fecha_ultimo_cambio',
        ),
        migrations.RemoveField(
            model_name='estadomaquina',
            name='motivo_estado',
        ),
        migrations.RemoveField(
            model_name='estadomaquina',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='estadomaquina',
            name='capacidad_hora',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad nominal por hora', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='estadomaquina',
            name='factor_eficiencia',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='estadomaquina',
            name='hora_fin_normal',
            field=models.TimeField(default=datetime.time(17, 45)),
        ),
        migrations.AddField(
            model_name='estadomaquina',
            name='hora_inicio_normal',
            field=models.TimeField(default=datetime.time(7, 45)),
        ),
        migrations.AlterField(
            model_name='estadomaquina',
            name='maquina',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.maquina'),
        ),
        migrations.AlterField(
            model_name='estadomaquina',
            name='tipos_maquina',
            field=models.ManyToManyField(to='Machine.tipomaquina'),
        ),
        migrations.CreateModel(
            name='DisponibilidadMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('motivo_no_disponible', models.TextField(blank=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='BloqueoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.TextField()),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine.disponibilidadmaquina')),
            ],
            options={
                'verbose_name': 'Bloqueo de Máquina',
                'verbose_name_plural': 'Bloqueos de Máquinas',
            },
        ),
    ]
