# Generated by Django 5.2 on 2025-04-24 20:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JobManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='JobManagement.empresaot')),
            ],
        ),
        migrations.CreateModel(
            name='OperadorMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_habilitacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.maquina')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operator.operador')),
            ],
            options={
                'verbose_name': 'Habilitación de máquina',
                'verbose_name_plural': 'Habilitaciónes de máquinas',
                'unique_together': {('operador', 'maquina')},
            },
        ),
        migrations.AddField(
            model_name='operador',
            name='maquinas_habilitadas',
            field=models.ManyToManyField(related_name='operadores_habilitados', through='Operator.OperadorMaquina', to='JobManagement.maquina'),
        ),
        migrations.CreateModel(
            name='AsignacionOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('item_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.itemruta')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.programaproduccion')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='Operator.operador')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='check_fecha_fin_mayor_inicio')],
            },
        ),
    ]
